import { lib, game, ui, get, ai, _status } from "../../../../../noname.js";
import { basic } from "../../basic.js";
export const character = async function () {
	var pack = {
		character: {
			qsmx_yorigami_yhion_and_yorigami_jyoon: [
				"female",
				"shen",
				4,
				["qsmx_eshen", "qsmx_chonggou"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_yorigami_yhion_and_yorigami_jyoon.jpg",
					"name:依神|紫苑-依神|女苑",
					"unseen",
				],
			],
			qsmx_junko: [
				"female",
				"shen",
				6,
				["junko_chunhua", "junko_shenxing", "junko_shenji", "junko_shenqu"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_junko.jpg",
					"name:null|null",
					"forbidai",
				],
			],
			qsmx_mimidog: [
				"male",
				"key",
				'6/6/0',
				["qsmx_cizhang", "qsmx_zhangming", "qsmx_zhangcai", "qsmx_xumiao"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_mimidog.jpg",
					"InitFilter:noZhuHp",
					"name:null|null",
					"forbidai",
				],
			],
			qsmx_longinus: [
				"male",
				"western",
				4,
				["qsmx_shishen", "qsmx_longinusSkill", "qsmx_zhouqu"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_longinus.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_longinus.mp3",
					"null|null",
					"forbidai",
				],
			],
			qsmx_xusha: [
				"male",
				"qun",
				3,
				["qsmx_yingmen", "qsmx_pingjian"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_xusha.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_xusha.mp3",
				],
			],
			qsmx_huangzhong: [
				"male",
				"shu",
				"4/4",
				["qsmx_liegong", "qsmx_fushe", "qsmx_shidi"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_huangzhong.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_huangzhong.mp3",
					"forbidai",
				],
			],
			qsmx_hw_sunquan: [
				"male",
				"wu",
				"4/4",
				["rezhiheng", "rejiuyuan", "qsmx_huiwan", "qsmx_winwin"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_hw_sunquan.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_hw_sunquan.mp3",
					"forbidai",
				],
			],
			qsmx_sunquan: [
				"male",
				"wu",
				"4/4",
				["qsmx_zhiheng", "rejiuyuan"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_sunquan.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_sunquan.mp3",
					"zhu",
				],
			],
			qsmx_baozheng: [
				"male",
				"qun",
				"1/12",
				["qsmx_difu", "qsmx_guiwang", "qsmx_xingpan", "qsmx_mingqu"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_baozheng.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_baozheng.mp3",
					"forbidai",
				],
			],
			qsmx_hw_zhonghui: [
				"male",
				"wei",
				"4/4",
				["xinquanji", "xinzili", "qsmx_huiwan"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_hw_zhonghui.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_hw_zhonghui.mp3",
					"forbidai",
				],
			],
			qsmx_luxun: [
				"male",
				"wu",
				"4/4",
				["qsmx_qianxun", "qsmx_dinghuo", "qmsx_lianying"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_luxun.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_luxun.mp3",
				],
			],
			qsmx_sunce: [
				"male",
				"wu",
				"4/4",
				["qsmx_jiang", "qsmx_hunyou", "qsmx_taoni"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_sunce.jpg",
					"zhu",
					"die:ext:奇思妙想/resource/audio/die/qsmx_sunce.mp3",
					"forbidai",
				],
			],
			qsmx_liubei: [
				"male",
				"qun",
				"4/4",
				[],
				[
					"ext:奇思妙想/resource/image/character/qsmx_liubei.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_liubei.mp3",
					"unseen"
				],
			],
			qsmx_cailun: [
				"male",
				"qun",
				"3/3",
				["qsmx_zaozhi", "qsmx_yishua"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_cailun.jpg",
					"forbidai",
				],
			],
			qsmx_SevenGod: [
				"female",
				"shen",
				"7/7",
				["qsmx_qichong", "qsmx_shenwei", "qsmx_shiyuan"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_SevenGod.jpg",
					"null|null",
					"forbidai",
				],
			],
			qsmx_jiaxu: [
				"male",
				"wei",
				"4/4",
				["qsmx_weimu", "qsmx_yanmie"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_jiaxu.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_jiaxu.mp3",
					"forbidai",
				],
			],
			qsmx_wangshuang: [
				"male",
				"wei",
				"8/8",
				["qsmx_zhuilie"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_wangshuang.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_wangshuang.mp3",
				],
			],
			qsmx_nanhualaoxian: [
				"male",
				"qun",
				"3/3",
				["qsmx_yizhao", "qsmx_linghua", "qsmx_xukong"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_nanhua.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_nanhua.mp3",
					"name:庄|周",
				],
			],
			qsmx_matara_okina: [
				"female",
				"shen",
				"4/4",
				["qsmx_mishen"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_matara_okina.jpg",
					"name:摩多罗|隐岐奈",
				],
			],
			qsmx_cenhun: [
				"male",
				"wu",
				"6/6",
				["qsmx_liancai", "jishe", "lianhuo"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_cenhun.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_cenhun.mp3",
				],
			],
			qsmx_zhenji: [
				"female",
				"wei",
				"3/3",
				["qsmx_luoshen", "qsmx_qingguo"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_zhenji.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_zhenji.mp3",
				],
			],
			qsmx_zhengxie: [
				"female",
				"key",
				"1/2",
				["qsmx_winwin","qsmx_tianxie"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_zhengxie.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_zhengxie.mp3",
					"name:鬼人|正邪",
					"forbidai",
				],
			],
			qsmx_guanyu: [
				"male",
				"shu",
				"4/4",
				["qsmx_wusheng", "qsmx_yijue"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_guanyu.jpg",
					"die:ext:奇思妙想/resource/audio/die/qsmx_guanyu.mp3",
				],
			],
			qsmx_caocao: [
				"male",
				"wei",
				"4/4",
				["qsmx_jianxiong", ,"qsmx_guixin", "rehujia"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_caocao.jpg",
					"zhu",
				],
			],
			qsmx_caopi: [
				"male",
				"wei",
				"3/3",
				["qsmx_xingshang", "qsmx_fangzhu", "songwei"],
				["ext:奇思妙想/resource/image/character/qsmx_caopi.jpg", "zhu"],
			],
			qsmx_caorui: [
				"male",
				"wei",
				"3/3/1",
				["qsmx_huituo", "qsmx_mingjian", "xingshuai"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_caorui.jpg",
					"zhu",
				],
			],
			qsmx_menghuo: [
				"male",
				"qun",
				"4/7",
				["qsmx_manqin", "qsmx_zaiqi"],
				["ext:奇思妙想/resource/image/character/qsmx_menghuo.jpg"],
			],
			qsmx_huatuo: [
				"male",
				"qun",
				"3/3",
				["qsmx_jishi", "qsmx_jingyu"],
				["ext:奇思妙想/resource/image/character/qsmx_huatuo.jpg"],
			],
			qsmx_zhangliao: [
				"male",
				"wei",
				"4/4",
				["qsmx_tuxi"],
				["ext:奇思妙想/resource/image/character/qsmx_zhangliao.jpg"],
			],
			qsmx_sp_zhangliao: [
				"male",
				"qun",
				"4/4",
				["qsmx_sp_tuxi"],
				["ext:奇思妙想/resource/image/character/qsmx_sp_zhangliao.jpg"],
			],
			qsmx_puyuan: [
				"male",
				"shu",
				"4/4",
				["qsmx_shengong", "qsmx_tianjiang"],
				["ext:奇思妙想/resource/image/character/qsmx_puyuan.jpg"],
			],
			qsmx_simashi: [
				"male",
				"jin",
				"3/4",
				["qsmx_taoyin", "qsmx_yimie", "qsmx_tairan", "qsmx_ruilve"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_simashi.jpg",
					"zhu",
					"hiddenSkill",
					"name:司马|师",
					"forbidai",
				],
			],
			qsmx_simayi: [
				"male",
				"wei",
				"3/3",
				["qsmx_renshi", "qsmx_quanbian", "qsmx_lianpo"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_simayi.jpg",
					"zhu",
					"name:司马|懿",
				],
			],
			qsmx_zhangxianzhong: [
				"male",
				"key",
				"4/7",
				["qsmx_tudiao", "qsmx_qisha", "qsmx_xianzhong"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_zhangxianzhong.jpg",
					"forbidai",
				],
			],
			qsmx_zhangfei: [
				"male",
				"shu",
				"4/4",
				["qsmx_paoxiao", "qsmx_zhendan"],
				["ext:奇思妙想/resource/image/character/qsmx_zhangfei.jpg"],
			],
			qsmx_sunjian: [
				"male",
				"wu",
				"4/4",
				["qsmx_polu", "qsmx_juelie", "qsmx_yinghun"],
				["ext:奇思妙想/resource/image/character/qsmx_sunjian.jpg"],
			],
			qsmx_shen_zhangjiao: [
				"male",
				"shen",
				"3/3",
				[
					"qsmx_shen_yizhao",
					"qsmx_sanshou",
					"qsmx_sijun",
					"qsmx_tianjie",
				],
				[
					"ext:奇思妙想/resource/image/character/qsmx_shen_zhangjiao.jpg",
				],
			],
			qsmx_zhangjiao: [
				"male",
				"qun",
				"3/3/1",
				["qsmx_leiji", "qsmx_guidao", "qsmx_huangtian"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_zhangjiao.jpg",
					"zhu",
				],
			],
			qsmx_lvbu: [
				"male",
				"qun",
				"6/6",
				["qsmx_mowu", "qsmx_monu", "qsmx_moji", "qsmx_moqu"],
				["ext:奇思妙想/resource/image/character/qsmx_lvbu.jpg"],
			],
			qsmx_zuoci: [
				"male",
				"qun",
				"3/3",
				["qsmx_huashen", "qsmx_xinsheng"],
				["ext:奇思妙想/resource/image/character/qsmx_zuoci.jpg"],
			],
			qsmx_yemoxia: [
				"male",
				"key",
				"6/6",
				["qsmx_yinwu", "qsmx_yinan", "qsmx_guangshi"],
				["ext:奇思妙想/resource/image/character/qsmx_yemoxia.jpg", "name:null|null"],
			],
			qsmx_shen_zhangliao: [
				"male",
				"shen",
				"4/4",
				[],
				[
					"ext:奇思妙想/resource/image/character/qsmx_shen_zhangliao.jpg",
					"unseen",
				],
			],
			qsmx_zhangliang: [
				"male",
				"qun",
				"4/4",
				["qsmx_jijun", "qsmx_fangtong", "qsmx_liudian"],
				["ext:奇思妙想/resource/image/character/qsmx_zhangliang.jpg"],
			],
			qsmx_machao: [
				"male",
				"shu",
				"4/4",
				['mashu', 'qsmx_tieqi'],
				["ext:奇思妙想/resource/image/character/qsmx_machao.jpg"],
			],
			qsmx_kobe_bryant: [
				"male",
				"key",
				"8/8",
				['qsmx_zhouji', 'qsmx_zhuiji', 'qsmx_fuhuo'],
				["ext:奇思妙想/resource/image/character/qsmx_kobe_bryant.jpg", "name:布莱恩特|科比"],
			],
			qsmx_gocar: [
				"none",
				"key",
				"4/4",
				['qsmx_shima','qsmx_tongqu', "qsmx_zhengtong"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_gocar.jpg", 
					"name:null|null", 
				],
			],
			qsmx_doremy_sweet: [
				"female",
				"key",
				"4/4",
				["qsmx_huanmeng", "qsmx_zaomeng"],
				["ext:奇思妙想/resource/image/character/qsmx_doremy_sweet.jpg", "name:哆来咪|苏伊特"],
			],
			qsmx_shen_zhangfei: [
				"male",
				"shen",
				"4/4",
				[],
				["ext:奇思妙想/resource/image/character/qsmx_shen_zhangfei.jpg", "unseen"],
			],
			qsmx_shen_xunyu: [
				"male",
				"shen",
				"3/3",
				[],
				["ext:奇思妙想/resource/image/character/qsmx_shen_xunyu.jpg", "unseen"],
			],
			qsmx_zhaoyun: [
				"male",
				"shu",
				"4/4",
				["qsmx_longdan", "qsmx_juejing"],
				[
					"ext:奇思妙想/resource/image/character/qsmx_zhaoyun.jpg",
				],
			],
			qsmx_visual_studio_code: [
				"none",
				"key",
				"4/4",
				[
					"qsmx_search",
					"qsmx_xuxiang"
				],
				[
					"ext:奇思妙想/resource/image/character/qsmx_visual_studio_code.jpg",
					"forbidai",
				],
			],
		},
		characterTitle: {
			qsmx_longinus: "百夫长",
			qsmx_cailun: "纸圣",
			qsmx_luxun: "夷陵火神",
			qsmx_matara_okina: "究极的绝对秘神",
			qsmx_SevenGod: "反记叙存在",
		},
		characterIntro: {
			qsmx_cailun:"蔡伦（63年－121年），字敬仲，东汉桂阳郡人。 汉明帝永平末年（公元75年），蔡伦入宫给事；汉章帝建初年间（76-84年），升任小黄门；汉和帝继位后，升任中常侍， 后又兼任尚方令，监造刀剑器械 。永元十四年（102年）蔡伦在邓皇后的支持下 ，总结以往人们的造纸经验，革新造纸工艺，最终制成了“蔡侯纸”，并于元兴元年（公元105年）奏报朝廷，汉和帝下令推广他的造纸法 。建光元年（公元121年），邓太后崩逝，汉安帝亲政，蔡伦服毒自尽，享年59岁。  蔡伦富有才学，敦厚谨慎，常犯颜谏诤，匡正得失，是宦官中少见的品德。其性格孤傲高洁，每至假期便闭门谢客，从不结派弄权，因而被誉为“汉宦官之贤者”。蔡伦改进 （一说发明）的造纸术被列为中国古代“四大发明” ，对人类文化的传播和世界文明的进步做出了杰出的贡献，千百年来备受人们的尊崇 ，被纸工奉为造纸鼻祖、“纸圣”、“纸神” 。 麦克·哈特的《影响人类历史进程的100名人排行榜》中，蔡伦排在第七位 。美国《时代》周刊公布的“有史以来的最佳发明家”中蔡伦上榜 。2008年北京奥运会开幕式，特别展示了蔡伦改进（一说发明）的造纸术 。",
			qsmx_matara_okina:"摩多罗隐岐奈是东方系列中的官方角色，首次登场于东方天空璋，担任天空璋的六面Boss及EX面Boss。 是创立幻想乡的贤者之一，不过一直以来极少出现在世人眼中，拥有在万物背上制作门扉程度的能力。 究极的绝对秘神，神格极多，发动季节异变明面上是为了给二童子找继任者，真正目的则是引人注目。 在天空璋登场后也曾在小数点作和官方漫画登场，是比较活跃的新角色。 刚欲异闻中，她最早注意到了饕餮尤魔在血池地狱的异常行为，便一手主导了黑水异变。她暗中把消息透露给地上的众人，并派遣芙兰朵露击败饕餮尤魔，最终没有隐患地平息了骚动。 ",
			qsmx_SevenGod:"七角噬元神，网络共笔怪谈体系《SCP基金会》中登场的反记叙存在，又称七重毁灭者/非存在之主。其同时存在于多个叙事层面，并能够摧毁任意将其信息囊括到一定程度的叙事，已经有多个元虚构叙事层因其而亡。戏里的故事，戏外的现实，层层嵌套的叙事，有着真实与虚构的差别，但在本质上都是七角噬元神的毁灭目标。",
		},
		characterFilter: {
			qsmx_matara_okina: function (mode) {
				return false;
			},
		},
		characterSort: {
			mode_extension_奇思妙想: {
				qsmx_HellOfResistance: [
					"qsmx_huangzhong",
					"qsmx_baozheng",
					"qsmx_SevenGod",
					"qsmx_sunce",
					"qsmx_jiaxu",
					"qsmx_longinus",
					"qsmx_mimidog",
					"qsmx_simashi",
				],
				qsmx_huiwanxili: [
					"qsmx_xusha",
					"qsmx_hw_zhonghui",
					"qsmx_hw_sunquan",
				],
				qmsx_diy: [
					"qsmx_shen_xunyu",
					"qsmx_shen_zhangfei",
					"qsmx_liubei",
					"qsmx_simayi",
					"qsmx_sp_zhangliao",
					"qsmx_machao",
					"qsmx_zhangliang",
					"qsmx_shen_zhangliao",
					"qsmx_yemoxia",
					"qsmx_zuoci",
					"qsmx_lvbu",
					"qsmx_zhangjiao",
					"qsmx_shen_zhangjiao",
					"qsmx_sunjian",
					"qsmx_spzhangliao",
					"qsmx_zhangfei",
					"qsmx_puyuan",
					"qsmx_sunquan",
					"qsmx_menghuo",
					"qsmx_caorui",
					"qsmx_caopi",
					"qsmx_caocao",
					"qsmx_huatuo",
					"qsmx_zhangliao",
					"qsmx_guanyu",
					"qsmx_zhenji",
					"qsmx_luxun",
					"qsmx_cailun",
					"qsmx_wangshuang",
					"qsmx_nanhualaoxian",
					"qsmx_cenhun",
				],
				qsmx_touhou: ["qsmx_matara_okina", "qsmx_zhengxie", "qsmx_junko", "qsmx_doremy_sweet"],
				qsmx_meme: ['qsmx_kobe_bryant', "qsmx_zhangxianzhong", "qsmx_gocar", "qsmx_visual_studio_code"]
			},
		},
		translate: {
			//武将分包
			qsmx_HellOfResistance: "纯粹的抗性地狱",
			qsmx_huiwanxili: "会玩系列武将",
			qsmx_meme: "仅供娱乐",
			qmsx_diy: "DIY武将",
			qsmx_touhou: "东方武将",
			//武将名
			qsmx_visual_studio_code: "Visual Studio Code",
			qsmx_visual_studio_code_ab: "VSCode",
			qsmx_zhaoyun: "妙赵云",
			qsmx_shen_xunyu: "妙神荀彧",
			qsmx_shen_zhangfei:"妙神张飞",
			qsmx_hw_sunquan: "会玩孙权",
			qsmx_hw_zhonghui: "会玩钟会",
			qsmx_shen_zhangliao: "妙神张辽",
			qsmx_yorigami_yhion_and_yorigami_jyoon: "依神紫苑&依神女苑",
			qsmx_yorigami_yhion_and_yorigami_jyoon_ab: "依神姐妹",
			qsmx_doremy_sweet: "哆来咪·苏伊特",
			qsmx_doremy_sweet_ab:"哆来咪",
			qsmx_kobe_bryant: "科比·布莱恩特",
			qsmx_kobe_bryant_ab: "科比",
			qsmx_zhangfei: "妙张飞",
			qsmx_zhangjiao: "妙张角",
			qsmx_sp_zhangliao: "SP妙张辽",
			qsmx_caorui: "妙曹叡",
			qsmx_liubei: "妙刘备",
			qsmx_simayi: "妙司马懿",
			qsmx_puyuan: "妙蒲元",
			qsmx_sunjian: "妙孙坚",
			qsmx_zhangliao: "妙张辽",
			qsmx_huatuo: "妙华佗",
			qsmx_zhangliang: "妙张梁",
			qsmx_gocar: "游卡桌游",
			qsmx_caopi: "妙曹丕",
			qsmx_machao: "妙马超",
			qsmx_zhengxie: "鬼人正邪",
			qsmx_menghuo: "妙孟获",
			qsmx_caocao: "妙曹操",
			qsmx_zhangxianzhong: "张献忠",
			qsmx_shen_zhangjiao: "妙神张角",
			qsmx_mimidog: "眯咪狗",
			qsmx_guanyu: "妙关羽",
			qsmx_zhenji: "妙甄宓",
			qsmx_zuoci: "妙左慈",
			qsmx_lvbu: "妙吕布",
			qsmx_cenhun: "妙岑昏",
			qsmx_simashi: "妙司马师",
			qsmx_huangzhong: "妙黄忠",
			qsmx_longinus: "朗基努斯",
			qsmx_yemoxia: "夜魔侠",
			qsmx_baozheng: "妙包拯",
			qsmx_sunce: "妙孙策",
			qsmx_xusha: "妙许劭",
			qsmx_sunquan: "妙孙权",
			qsmx_zhonghui: "妙钟会",
			qsmx_luxun: "妙陆逊",
			qsmx_cailun: "蔡伦",
			qsmx_SevenGod: "七重毁灭者",
			qsmx_jiaxu: "妙贾诩",
			qsmx_wangshuang: "妙王双",
			qsmx_nanhualaoxian: "妙南华老仙",
			qsmx_matara_okina: "摩多罗隐岐奈",
		},
	};
	return pack;
};
